# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_PivotWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pivot(object):
    def setupUi(self, Pivot):
        Pivot.setObjectName("Pivot")
        Pivot.resize(1026, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Pivot.sizePolicy().hasHeightForWidth())
        Pivot.setSizePolicy(sizePolicy)
        Pivot.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        Pivot.setFont(font)
        Pivot.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Pivot.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(Pivot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMinimumSize(QtCore.QSize(800, 500))
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.centralWidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        Pivot.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Pivot)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1026, 23))
        self.menuBar.setMinimumSize(QtCore.QSize(0, 23))
        self.menuBar.setAutoFillBackground(False)
        self.menuBar.setStyleSheet("background-color: rgb(239, 239, 239);\n"
"font: 75 9pt \"Microsoft YaHei UI\";")
        self.menuBar.setObjectName("menuBar")
        self.menumenu_A = QtWidgets.QMenu(self.menuBar)
        self.menumenu_A.setObjectName("menumenu_A")
        self.menumenu_B = QtWidgets.QMenu(self.menuBar)
        self.menumenu_B.setObjectName("menumenu_B")
        Pivot.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Pivot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainToolBar.sizePolicy().hasHeightForWidth())
        self.mainToolBar.setSizePolicy(sizePolicy)
        self.mainToolBar.setMinimumSize(QtCore.QSize(0, 23))
        self.mainToolBar.setObjectName("mainToolBar")
        Pivot.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Pivot)
        self.statusBar.setObjectName("statusBar")
        Pivot.setStatusBar(self.statusBar)
        self.actiontool_A = QtWidgets.QAction(Pivot)
        self.actiontool_A.setObjectName("actiontool_A")
        self.actiontool_B = QtWidgets.QAction(Pivot)
        self.actiontool_B.setObjectName("actiontool_B")
        self.actiontool_C = QtWidgets.QAction(Pivot)
        self.actiontool_C.setObjectName("actiontool_C")
        self.actiontool_D = QtWidgets.QAction(Pivot)
        self.actiontool_D.setObjectName("actiontool_D")
        self.actiontool_A_2 = QtWidgets.QAction(Pivot)
        self.actiontool_A_2.setObjectName("actiontool_A_2")
        self.actiontool_B_2 = QtWidgets.QAction(Pivot)
        self.actiontool_B_2.setObjectName("actiontool_B_2")
        self.actiontool_import = QtWidgets.QAction(Pivot)
        self.actiontool_import.setObjectName("actiontool_import")
        self.actiontool_label = QtWidgets.QAction(Pivot)
        self.actiontool_label.setObjectName("actiontool_label")
        self.actionmenu_A1 = QtWidgets.QAction(Pivot)
        self.actionmenu_A1.setObjectName("actionmenu_A1")
        self.actionmenu_A2 = QtWidgets.QAction(Pivot)
        self.actionmenu_A2.setObjectName("actionmenu_A2")
        self.actionmenu_A3 = QtWidgets.QAction(Pivot)
        self.actionmenu_A3.setObjectName("actionmenu_A3")
        self.menumenu_A.addAction(self.actionmenu_A1)
        self.menumenu_A.addAction(self.actionmenu_A2)
        self.menumenu_A.addAction(self.actionmenu_A3)
        self.menuBar.addAction(self.menumenu_A.menuAction())
        self.menuBar.addAction(self.menumenu_B.menuAction())
        self.mainToolBar.addAction(self.actiontool_import)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actiontool_label)

        self.retranslateUi(Pivot)
        QtCore.QMetaObject.connectSlotsByName(Pivot)

    def retranslateUi(self, Pivot):
        _translate = QtCore.QCoreApplication.translate
        Pivot.setWindowTitle(_translate("Pivot", "Pivot Window"))
        self.menumenu_A.setTitle(_translate("Pivot", "menu_A"))
        self.menumenu_B.setTitle(_translate("Pivot", "menu_B"))
        self.actiontool_A.setText(_translate("Pivot", "tool_A"))
        self.actiontool_A.setToolTip(_translate("Pivot", "tool_A"))
        self.actiontool_B.setText(_translate("Pivot", "tool_B"))
        self.actiontool_B.setToolTip(_translate("Pivot", "tool_B"))
        self.actiontool_C.setText(_translate("Pivot", "tool_C"))
        self.actiontool_C.setToolTip(_translate("Pivot", "tool_C"))
        self.actiontool_D.setText(_translate("Pivot", "tool_D"))
        self.actiontool_D.setToolTip(_translate("Pivot", "tool_D"))
        self.actiontool_A_2.setText(_translate("Pivot", "tool_A"))
        self.actiontool_A_2.setToolTip(_translate("Pivot", "tool_A"))
        self.actiontool_B_2.setText(_translate("Pivot", "tool_B"))
        self.actiontool_B_2.setToolTip(_translate("Pivot", "tool_B"))
        self.actiontool_import.setText(_translate("Pivot", "import"))
        self.actiontool_import.setToolTip(_translate("Pivot", "import"))
        self.actiontool_label.setText(_translate("Pivot", "actiontool_label"))
        self.actiontool_label.setToolTip(_translate("Pivot", "actiontool_label"))
        self.actionmenu_A1.setText(_translate("Pivot", "menu_A1"))
        self.actionmenu_A2.setText(_translate("Pivot", "menu_A2"))
        self.actionmenu_A3.setText(_translate("Pivot", "menu_A3"))
